import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const CORS={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const P={type:"object",additionalProperties:false,properties:{x:{type:"number"},y:{type:"number"}},required:["x","y"]};
const SEG={type:"object",additionalProperties:false,properties:{x1:{type:"number"},y1:{type:"number"},x2:{type:"number"},y2:{type:"number"},tipo:{type:"string"},confianza:{type:"string",enum:["alta","media","baja"]}},required:["x1","y1","x2","y2","tipo","confianza"]};
const SCHEMA={
  type:"object",additionalProperties:false,properties:{
    documento:{type:"object",additionalProperties:false,properties:{codigo:{type:"string"},revision:{type:"string"},unidades:{type:"string"},paginas_utiles:{type:"array",items:{type:"integer"}}},required:["codigo","revision","unidades","paginas_utiles"]},
    envolvente:{type:"object",additionalProperties:false,properties:{ancho:{type:"number"},largo:{type:"number"}},required:["ancho","largo"]},
    grid:{type:"object",additionalProperties:false,properties:{horizontal:{type:"array",items:{type:"number"}},vertical:{type:"array",items:{type:"number"}}},required:["horizontal","vertical"]},
    areas:{type:"array",items:{type:"object",additionalProperties:false,properties:{nombre:{type:"string"},tipo:{type:"string",enum:["open","privado","juntas","recepcion","lounge","servicio"]},forma:{type:"string",enum:["poligono","circulo"]},puntos:{type:"array",items:P},circulo:{type:"object",additionalProperties:false,properties:{cx:{type:"number"},cy:{type:"number"},r:{type:"number"}},required:["cx","cy","r"]},dentroDe:{type:"string"},puestos:{type:"integer"},confianza:{type:"string",enum:["alta","media","baja"]}},required:["nombre","tipo","forma","puntos","circulo","dentroDe","puestos","confianza"]}},
    muros:{type:"array",items:SEG},
    puertas:{type:"array",items:{type:"object",additionalProperties:false,properties:{x:{type:"number"},y:{type:"number"},ancho:{type:"number"},orientacion:{type:"string"},conecta:{type:"array",items:{type:"string"}},confianza:{type:"string",enum:["alta","media","baja"]}},required:["x","y","ancho","orientacion","conecta","confianza"]}},
    ventanas:{type:"array",items:SEG},
    cotas:{type:"array",items:{type:"object",additionalProperties:false,properties:{valor_mm:{type:"number"},etiqueta:{type:"string"},tipo:{type:"string",enum:["general","eje","recinto","elemento","otra"]},pagina:{type:"integer"},confianza:{type:"string",enum:["alta","media","baja"]}},required:["valor_mm","etiqueta","tipo","pagina","confianza"]}},
    acabados:{type:"array",items:{type:"object",additionalProperties:false,properties:{scope:{type:"string",enum:["area","mobiliario","global"]},target:{type:"string"},categoria:{type:"string"},valor:{type:"string"},pagina:{type:"integer"},confianza:{type:"string",enum:["alta","media","baja"]}},required:["scope","target","categoria","valor","pagina","confianza"]}},
    equipamiento:{type:"array",items:{type:"object",additionalProperties:false,properties:{id:{type:"string"},producto:{type:"string"},cantidad:{type:"integer"},ancho_mm:{type:"number"},fondo_mm:{type:"number"},capacidad:{type:"integer"},acabado:{type:"string"},area:{type:"string"},confianza:{type:"string",enum:["alta","media","baja"]}},required:["id","producto","cantidad","ancho_mm","fondo_mm","capacidad","acabado","area","confianza"]}},
    escala:{type:"string"},tieneCotas:{type:"boolean"},notas:{type:"array",items:{type:"string"}},evidencias:{type:"array",items:{type:"string"}}
  },required:["documento","envolvente","grid","areas","muros","puertas","ventanas","cotas","acabados","equipamiento","escala","tieneCotas","notas","evidencias"]
};

Deno.serve(async(req:Request)=>{
  if(req.method==="OPTIONS") return new Response("ok",{headers:CORS});
  if(req.method!=="POST") return json({ok:false,code:"METHOD_NOT_ALLOWED",error:"Usa POST"},405);
  const key=Deno.env.get("ANTHROPIC_API_KEY"); if(!key) return json({ok:false,code:"SERVER_CONFIG",error:"Falta ANTHROPIC_API_KEY"},500);
  let body:any; try{body=await req.json()}catch{return json({ok:false,code:"INVALID_JSON",error:"JSON inválido"},400)}
  const {image,mediaType="image/jpeg",refMM}=body||{}; if(!image) return json({ok:false,code:"MISSING_IMAGE",error:"Falta el plano"},400);
  const esPdf=mediaType==="application/pdf";
  const system=`Eres Document Intelligence especializado en planos arquitectónicos de oficinas. Tu salida NO es una interpretación creativa: es un levantamiento trazable del documento.\n\nOBJETIVO: extraer geometría + restricciones + semántica + acabados/equipamiento sin mezclar páginas ni inventar.\n\nORDEN OBLIGATORIO:\n1. Identifica páginas que contienen planta, cuadro de acabados/equipamiento y notas.\n2. Fija escala/envolvente usando COTAS impresas; cota explícita > barra de escala > referencia del usuario > estimación.\n3. Traza cada área con coordenadas absolutas en mm desde esquina superior izquierda. No conviertas polígonos irregulares en bounding boxes.\n4. Extrae MUROS/particiones como segmentos. Diferencia exterior/interior/partición. No confundas cotas, mobiliario ni líneas HVAC con muros.\n5. Extrae TODAS las puertas/vanos y ventanas. La puerta debe caer sobre un muro; usa el arco de giro sólo como evidencia del vano.\n6. Extrae COTAS estructuradas: generales, ejes, recintos y elementos. Conserva página y confianza.\n7. Extrae ACABADOS visibles en leyendas/tablas/notas; si pertenecen a mobiliario, scope='mobiliario'. No inventes acabados por color del dibujo.\n8. Extrae EQUIPAMIENTO sólo de tablas/labels explícitos. Cantidad de puestos NO se infiere contando patas/sillas; si el documento declara '8 puestos exactos', puestos=8.\n9. Sanitarios/SITE/ductos/bodega son servicio y no se amueblan.\n\nCOORDENADAS: origen (0,0) esquina superior izquierda; x→derecha, y→abajo; mm absolutos. Curvas: 8-16 puntos. Círculos reales: centro/radio.\n\nAUTOCHEQUEO antes de responder: envolvente coincide con cota general; suma de grid cuadra; puntos dentro del envolvente; puertas cerca de muros; áreas no anidadas no exceden superficie; no duplicaste puestos; no usaste la página de tabla como geometría.${refMM?` Referencia aportada por usuario: ${refMM} mm.`:""}`;
  const apiBody={model:"claude-opus-5",max_tokens:12000,output_config:{effort:"high",format:{type:"json_schema",schema:SCHEMA}},system,messages:[{role:"user",content:[esPdf?{type:"document",source:{type:"base64",media_type:"application/pdf",data:image}}:{type:"image",source:{type:"base64",media_type:mediaType,data:image}},{type:"text",text:"Levanta este documento completo. Prioriza evidencia explícita y marca baja confianza cuando no puedas demostrar algo."}]}]};
  let data:any; try{const r=await fetch("https://api.anthropic.com/v1/messages",{method:"POST",headers:{"content-type":"application/json","x-api-key":key,"anthropic-version":"2023-06-01"},body:JSON.stringify(apiBody)}); data=await r.json(); if(!r.ok) return json({ok:false,code:"UPSTREAM_ERROR",error:data?.error?.message||`Anthropic ${r.status}`},502);}catch(e){return json({ok:false,code:"UPSTREAM_UNREACHABLE",error:"No se pudo llamar a Document Intelligence: "+String(e)},502)}
  if(data?.stop_reason==="refusal") return json({ok:false,code:"VISION_REFUSAL",error:"No se pudo leer el plano."},422);
  const txt=(data?.content||[]).find((b:any)=>b.type==="text")?.text||""; let lectura:any; try{lectura=JSON.parse(txt)}catch{return json({ok:false,code:"UPSTREAM_INVALID_JSON",error:"Document Intelligence no devolvió JSON válido."},502)}
  return json({ok:true,version:"DOCUMENT_INTELLIGENCE_V2",lectura,uso:data?.usage||null});
});
function json(obj:unknown,status=200){return new Response(JSON.stringify(obj),{status,headers:{...CORS,"content-type":"application/json"}})}
