import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";
const CORS={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const TASKS=new Set(["review_product","interpret_change","plan_review","layout_review","quote_review","cost_review","general"]);
const SELLER_BLOCKED=/^(costo.*|cost.*|margen.*|margin.*|utilidad.*|profit.*|precioproveedor.*|supplier(price|cost).*|precio_compra.*|purchaseprice.*|internal.*econom.*)$/i;
const COUNCIL_SCHEMA={type:"object",properties:{decision:{type:"string",enum:["APPLY_EXPLICIT_CHANGE","PROPOSE_OPTIONS","ASK_CRITICAL_QUESTION","NO_CHANGE","REQUIRES_VALIDATION","BLOCK"]},summary:{type:"string"},facts:{type:"array",items:{type:"object",properties:{what:{type:"string"},evidence:{type:"string"}},required:["what","evidence"],additionalProperties:false}},inferences:{type:"array",items:{type:"object",properties:{what:{type:"string"},confidence:{type:"string",enum:["HIGH","MEDIUM","LOW"]},why:{type:"string"}},required:["what","confidence","why"],additionalProperties:false}},recommendations:{type:"array",items:{type:"object",properties:{category:{type:"string",enum:["DESIGN","ENGINEERING","MATERIALS","MANUFACTURING","COST","SPACE","COMMERCIAL","RISK"]},what:{type:"string"},why:{type:"string"},impact:{type:"string"},confidence:{type:"string",enum:["HIGH","MEDIUM","LOW"]},requires_validation:{type:"boolean"}},required:["category","what","why","impact","confidence","requires_validation"],additionalProperties:false}},questions:{type:"array",items:{type:"object",properties:{what:{type:"string"},information_gain:{type:"string",enum:["HIGH","MEDIUM","LOW"]}},required:["what","information_gain"],additionalProperties:false}},proposed_actions:{type:"array",items:{type:"object",properties:{type:{type:"string"},payload:{type:"object",properties:{summary:{type:"string"}},required:["summary"],additionalProperties:false}},required:["type","payload"],additionalProperties:false}},blockers:{type:"array",items:{type:"string"}}},required:["decision","summary","facts","inferences","recommendations","questions","proposed_actions","blockers"],additionalProperties:false};
function sanitize(v:unknown,s:boolean):unknown{if(!s)return v;if(Array.isArray(v))return v.map(x=>sanitize(x,true));if(v&&typeof v==='object'){const o:Record<string,unknown>={};for(const[k,x]of Object.entries(v as Record<string,unknown>)){const nk=k.replace(/[^a-z0-9_]/gi,'').toLowerCase();if(SELLER_BLOCKED.test(nk))continue;o[k]=sanitize(x,true)}return o}return v}
function asJson(t:string){if(!t)return null;const x=t.trim().replace(/^```(?:json)?\s*/i,'').replace(/```\s*$/i,'').trim();try{return JSON.parse(x)}catch{}const a=x.indexOf('{'),b=x.lastIndexOf('}');if(a>=0&&b>a){try{return JSON.parse(x.slice(a,b+1))}catch{}}return null}
function valid(x:any){return !!x&&typeof x==='object'&&typeof x.decision==='string'&&typeof x.summary==='string'&&Array.isArray(x.facts)&&Array.isArray(x.inferences)&&Array.isArray(x.recommendations)&&Array.isArray(x.questions)&&Array.isArray(x.proposed_actions)&&Array.isArray(x.blockers)}
const RULES=`Devuelve exactamente el JSON solicitado. Sé conciso: máximo 5 hechos, 5 inferencias, 3 recomendaciones, 3 preguntas, 3 acciones propuestas y 5 bloqueos; cada texto debe ser breve. No inventes cifras ni capacidades; no certifiques ingeniería; separa hechos de inferencias; si falta evidencia crítica usa REQUIRES_VALIDATION o ASK_CRITICAL_QUESTION; no digas que una acción fue ejecutada porque aquí sólo razonas/propones. En proposed_actions.payload usa summary; no es ejecutable.`;
function sys(task:string,role:string){return `Eres VONI Council, capa de razonamiento experta para Von Haucke. Tu salida NO ejecuta herramientas: propone y critica; el sistema determinista decide y ejecuta.\nTarea: ${task}. Rol del usuario: ${role}.\nPiensa como equipo de diseño, ingeniería, materiales, manufactura, costeo, space planning y comercial, activando sólo lo relevante.\nPrioriza seguridad, trazabilidad, manufacturabilidad, mantenimiento, claridad y valor económico. Nunca reveles economía interna si el contexto no la contiene.\n${RULES}`}
function providerBudget(task:string){return task==='review_product'?22000:task==='interpret_change'?14000:18000}
async function timeout<T>(ms:number,fn:(s:AbortSignal)=>Promise<T>){const a=new AbortController(),t=setTimeout(()=>a.abort(),ms);try{return await fn(a.signal)}finally{clearTimeout(t)}}
async function anthropic(k:string,task:string,role:string,input:any){const model=Deno.env.get('ANTHROPIC_MODEL')||'claude-opus-5',t=Date.now();try{const j:any=await timeout(providerBudget(task),async signal=>{const r=await fetch('https://api.anthropic.com/v1/messages',{method:'POST',headers:{'content-type':'application/json','x-api-key':k,'anthropic-version':'2023-06-01'},body:JSON.stringify({model,max_tokens:2600,system:sys(task,role),messages:[{role:'user',content:[{type:'text',text:JSON.stringify(input)}]}],output_config:{format:{type:'json_schema',schema:COUNCIL_SCHEMA}}}),signal});const x=await r.json();if(!r.ok||x?.type==='error')throw new Error(x?.error?.message||`Anthropic HTTP ${r.status}`);return x});const text=(j?.content||[]).filter((b:any)=>b.type==='text').map((b:any)=>b.text||'').join('');const out=asJson(text);if(!valid(out))throw new Error(`Anthropic salida estructurada inválida${j?.stop_reason?` (${j.stop_reason})`:''}`);return{provider:'anthropic',ok:true,model,ms:Date.now()-t,output:out}}catch(e){return{provider:'anthropic',ok:false,model,ms:Date.now()-t,error:String(e instanceof Error?e.message:e)}}}
function geminiText(j:any){if(typeof j?.output_text==='string'&&j.output_text)return j.output_text;return (j?.steps||[]).filter((s:any)=>s?.type==='model_output').flatMap((s:any)=>s?.content||[]).filter((c:any)=>c?.type==='text').map((c:any)=>c?.text||'').join('')}
async function gemini(k:string,task:string,role:string,input:any){const model=Deno.env.get('GEMINI_TEXT_MODEL')||'gemini-3.6-flash',t=Date.now();try{const j:any=await timeout(providerBudget(task),async signal=>{const r=await fetch('https://generativelanguage.googleapis.com/v1beta/interactions',{method:'POST',headers:{'content-type':'application/json','x-goog-api-key':k},body:JSON.stringify({model,input:sys(task,role)+'\n\nINPUT:\n'+JSON.stringify(input),response_format:{type:'text',mime_type:'application/json',schema:COUNCIL_SCHEMA}}),signal});const x=await r.json();if(!r.ok||x?.error)throw new Error(x?.error?.message||`Gemini HTTP ${r.status}`);if(x?.status&&x.status!=='completed')throw new Error(`Gemini interaction ${x.status}`);return x});const out=asJson(geminiText(j));if(!valid(out))throw new Error('Gemini salida estructurada inválida');return{provider:'gemini',ok:true,model,ms:Date.now()-t,output:out}}catch(e){return{provider:'gemini',ok:false,model,ms:Date.now()-t,error:String(e instanceof Error?e.message:e)}}}
async function openai(k:string,task:string,role:string,input:any){const model=Deno.env.get('OPENAI_MODEL'),t=Date.now();if(!model)return{provider:'openai',ok:false,skipped:true,ms:0,error:'OPENAI_MODEL no configurado'};try{const j:any=await timeout(providerBudget(task),async signal=>{const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{'content-type':'application/json','authorization':`Bearer ${k}`},body:JSON.stringify({model,input:sys(task,role)+'\n\nINPUT:\n'+JSON.stringify(input)}),signal});const x=await r.json();if(!r.ok||x?.error)throw new Error(x?.error?.message||`OpenAI HTTP ${r.status}`);return x});const text=j?.output_text||(j?.output||[]).flatMap((o:any)=>o?.content||[]).map((c:any)=>c?.text||'').join('')||'';const out=asJson(text);if(!valid(out))throw new Error('OpenAI JSON inválido');return{provider:'openai',ok:true,model,ms:Date.now()-t,output:out}}catch(e){return{provider:'openai',ok:false,model,ms:Date.now()-t,error:String(e instanceof Error?e.message:e)}}}
function consensus(rs:any[]){const ok=rs.filter(r=>r.ok&&r.output);if(!ok.length)return{status:'NO_PROVIDER',decision:'BLOCK',requires_confirmation:true,provider_decisions:[]};if(ok.length===1)return{status:'SINGLE_PROVIDER',decision:ok[0].output?.decision||'REQUIRES_VALIDATION',requires_confirmation:true,provider_decisions:ok.map(r=>({provider:r.provider,decision:r.output?.decision}))};const ds=ok.map(r=>r.output?.decision||'REQUIRES_VALIDATION'),same=ds.every(d=>d===ds[0]),critical=new Set(['BLOCK','REQUIRES_VALIDATION','ASK_CRITICAL_QUESTION']);if(!same)return{status:'DISAGREEMENT',decision:ds.some(d=>d==='BLOCK')?'BLOCK':'REQUIRES_VALIDATION',requires_confirmation:true,provider_decisions:ok.map(r=>({provider:r.provider,decision:r.output?.decision}))};return{status:'CONSENSUS',decision:ds[0],requires_confirmation:critical.has(ds[0]),provider_decisions:ok.map(r=>({provider:r.provider,decision:r.output?.decision}))}}
function hash(s:string){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return(h>>>0).toString(16).padStart(8,'0')}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:CORS});if(req.method!=='POST')return json({ok:false,error:'Usa POST'},405);const URL=Deno.env.get('SUPABASE_URL'),SERVICE=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY'),ANON=Deno.env.get('SUPABASE_ANON_KEY');if(!URL||!SERVICE)return json({ok:false,error:'Falta configuración del servidor'},500);const ah=req.headers.get('Authorization')||'';if(!ah.startsWith('Bearer '))return json({ok:false,error:'No autenticado'},401);const uc=createClient(URL,ANON||SERVICE,{global:{headers:{Authorization:ah}}});const{data:ud}=await uc.auth.getUser();const email=ud?.user?.email||'';if(!email)return json({ok:false,error:'Sesión inválida'},401);const svc=createClient(URL,SERVICE);const{data:permit}=await svc.from('permitidos').select('rol').eq('email',email).maybeSingle();if(!permit)return json({ok:false,error:'Usuario no autorizado'},403);const role=String(permit.rol||'').toLowerCase(),sellerSafe=!['direccion','diseno'].includes(role);let body:any;try{body=await req.json()}catch{return json({ok:false,error:'JSON inválido'},400)}const task=String(body?.task||'general');if(!TASKS.has(task))return json({ok:false,error:'task no soportado'},400);const requestText=String(body?.request||body?.question||'').trim();if(!requestText)return json({ok:false,error:'Falta request'},400);const input={request:requestText.slice(0,12000),context:sanitize(body?.context||{},sellerSafe),explicit_constraints:Array.isArray(body?.constraints)?body.constraints.slice(0,50):[],requested_lenses:Array.isArray(body?.lenses)?body.lenses.slice(0,12):[]};const serialized=JSON.stringify(input);if(serialized.length>120000)return json({ok:false,error:'Contexto demasiado grande'},413);const ak=Deno.env.get('ANTHROPIC_API_KEY'),gk=Deno.env.get('GEMINI_API_KEY'),ok=Deno.env.get('OPENAI_API_KEY');if(!ak&&!gk&&!ok)return json({ok:false,error:'No hay proveedor AI configurado'},503);const start=Date.now(),calls:Promise<any>[]=[];
if(ak)calls.push(anthropic(ak,task,role,input));
if(gk)calls.push(gemini(gk,task,role,input));
if(ok)calls.push(openai(ok,task,role,input));
const budgetEnv=Number(Deno.env.get('VONI_COUNCIL_BUDGET_MS')||14500);
const councilBudget=Math.min(20000,Math.max(6000,Number.isFinite(budgetEnv)?budgetEnv:14500));
const completed:any[]=[];
const tracked=calls.map((p)=>p.then((r)=>{completed.push(r);return r;}));
let deadlineHit=false;
await Promise.race([
  Promise.all(tracked),
  new Promise<void>((resolve)=>setTimeout(()=>{deadlineHit=true;resolve();},councilBudget)),
]);
const results=[...completed],council=consensus(results),latency=Date.now()-start;try{await svc.from('voni_council_events').insert({email,rol:role,task,providers:results.map(r=>({provider:r.provider,ok:r.ok,model:r.model||null,ms:r.ms,skipped:!!r.skipped,error:r.ok?null:String(r.error||'').slice(0,500)})),status:council.status,decision:council.decision,request_hash:hash(serialized),latency_ms:latency})}catch{}return json({ok:results.some(r=>r.ok),task,seller_safe:sellerSafe,council,opinions:results,latency_ms:latency,deadline_hit:deadlineHit,execution:'PROPOSAL_ONLY',deterministic_validation_required:true},results.some(r=>r.ok)?200:502)});
function json(o:unknown,s=200){return new Response(JSON.stringify(o),{status:s,headers:{...CORS,'content-type':'application/json'}})}